### ISSUE TITLE
Storage: Search for a city, click on it, and menu hamburger disappears

### ISSUE THREAD

**Issue by mmerkes** [ionic-in-action/chapter7#1]
The repro was pretty simple:
1. Search for a city
2. Click on the city
3. On weather page, there is no menu hamburger

**Comment by gnomeontherun** [comment]
Now we don't want to lose the hamburgers now do we!

**Comment by mmerkes** [comment]
Yeah, it was probably the Hamburglar.

**Comment by gnomeontherun** [comment]
That was a bug in an older version of the app that came up from an Ionic update that didn't get fixed in this chapter. Fixed.
